config/routes.rb
Rails.application.routes.draw do
  devise_for :users
    root to: "pages#index"
    resources :pages do 
      member do
        get 'show_results'
      end
    end

end

app/models/answer.rb
class Answer < ActiveRecord::Base
	belongs_to :question
	belongs_to :user
end

app/models/question.rb
class Question < ActiveRecord::Base
	belongs_to :test
	has_many :answers

	def average_for_question
		return self.answers.select("value").inject(0) {|sum, i| sum+=i.value.to_i } / self.answers.count
	end

	def num_answers
		return self.answers.count
	end
end

app/models/step.rb
class Step < ActiveRecord::Base
end

app/models/test.rb
class Test < ActiveRecord::Base
	has_many :questions
	has_many :answers, :through => :questions
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	before_save { self.email = email.downcase }
	validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  has_many :answers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	before_action :authenticate_user!, only: [:new, :create]
  def index
  	@tests = Test.all
  end

  def new
  	@test = Test.find(params[:test_id])
  	@questions = @test.questions
  end

  def create 
  	answers = params[:question]
  	answers.each do |key, value|
  		Question.find(key).answers.build(:value => value, :user_id => User.first.id).save!
  	end
  	redirect_to root_path
  end

  def show_results
    @test = Test.find params[:id]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FosuboTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'shared/menu' %>

<%= yield %>

</body>
</html>

app/views/pages/index.html.erb
<% content_for :name_page do %>
  <%= image_tag("fosubo_logo.png") %>
<% end %>

<div class="container mt100">
	<div class="row">
		<div class="col-xs-6 col-xs-offset-3">
			<h2 class="text-center">Test disponibles</h2>		
			<table class="table table-condensed">
	      <thead>
	        <tr>
	          <th>#</th>
	          <th>Nombre</th>
	          <th>Tomar test</th>
	          <th>Ver resultados</th>
	        </tr>
	      </thead>
	      <tbody>
	      	<% @tests.each_with_index do |value,index| %>
		        <tr>
		          <th scope="row"><%= index + 1 %></th>
		          <td><%=value.name%></td>
		          <td>
		          	<%= link_to("Tomar", new_page_path(:test_id => value.id), html_options = {:class => "btn btn-blue btn"}) %>
		          </td>
		          <td>
		          	<%= link_to("Ver", show_results_page_path(:id => value.id), html_options = {:class => "btn btn-blue btn"}) %>
		          </td>
		        </tr>
	        <% end %>
	      </tbody>
	    </table>
		</div>
	</div>
</div>

app/views/pages/new.html.erb
<% content_for :name_page do %>
  <%= @test.name %>
<% end %>
<section class="container">
	<div class="row">
		<div class="col-xs-12">
			<%= form_tag pages_path, :method => 'post' do %>
			<% @questions.each do |q|%>
				<div class="question">
					<h3><%= q.sentence %></h3>
					<div class="row">
						<div class="col-xs-offset-1 col-xs-2">
							<div class="option0">
								<%= radio_button("question", q.id.to_s, "0", class: "grayborder redborder") %>
								<%= label("question", q.id.to_s + "_0", "0%")%>
							</div>
						</div>						
						<div class="col-xs-2">
							<div class="option1">
								<%= radio_button("question", q.id.to_s, "25", class: "grayborder orangeborder") %>
								<%= label("question", q.id.to_s + "_25", "25%")%>
							</div>
						</div>
						<div class="col-xs-2">
							<div class="option2">
								<%= radio_button("question", q.id.to_s, "50", class: "grayborder yellowborder") %>
								<%= label("question", q.id.to_s + "_50", "50%")%>
							</div>
						</div>
						<div class="col-xs-2">
							<div class="option3">
								<%= radio_button("question", q.id.to_s, "75", class: "grayborder turqoiseborder") %>
								<%= label("question", q.id.to_s + "_75", "75%")%>
							</div>
						</div>
						<div class="col-xs-2">
							<div class="option0">
								<%= radio_button("question", q.id.to_s.to_s, "100", class: "grayborder greenborder") %>
								<%= label("question", q.id.to_s.to_s + "_100", "100%")%>
							</div>
						</div>						
					</div>
				</div>
			<% end %>
			<div class="text-center mt30 col-xs-10 col-xs-offset-1">
				<%= submit_tag "NEXT",  class: "btn btn-info btn-lg btn-block btn-blue" %>
			</div>
			<% end %>
		</div>
	</div>
</section>

app/views/pages/show_results.html.erb
<% content_for :name_page do %>
  <%= @test.name %>
<% end %>

<div class="container ">
	<div class="row">
		<div class="col-xs-6 col-xs-offset-3">
			<h2 class="text-center">Test disponibles</h2>		
			<table class="table table-condensed">
	      <thead>
	        <tr>
	          <th>#</th>
	          <th>Pregunta</th>
	          <th>No. respuestas</th>
	          <th>Promedio</th>
	        </tr>
	      </thead>
	      <tbody>
	      	<% @test.questions.each_with_index do |value,index| %>
		        <tr>
		          <th scope="row"><%= index + 1 %></th>
		          <td><%=value.sentence%></td>
		          <td><%=value.num_answers%></td>
		          <td><%=value.average_for_question%>%</td>
		        </tr>
	        <% end %>
	      </tbody>
	    </table>
		</div>
	</div>
</div>

app/views/shared/_menu.html.erb
<!-- _menu.html.erb -->
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
  	<div class="row">
  		<div class="col-xs-3">
  			
  		</div>
  		<div class="col-xs-6">
  			<div class="name-brand">
  				<a href="/"><%= yield :name_page %></a>
  			</div>
  		</div>
  		<div class="col-xs-3">
        <ul class="devise-log">
          <% if user_signed_in? %>
            <li>
            <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
            </li>
          <% else %>
            <li>
            <%= link_to('Login', new_user_session_path)  %>  
            </li>
          <% end %></ul>
  		</div>
  	</div>    
  </div><!-- /.container -->
</nav>

<% flash.each do |name, msg| %>

  <% if msg.class == Array %>
    <% msg.each do |message| %>
      <%= content_tag :div, message, :id => "flash_#{name}" %>
    <% end %>
  <% else %>


    <%= content_tag :div, msg, :id => "flash_#{name}" %>

  <% end %> 
<% end %>